/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocalculadora;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;

/**
 *
 * @author JrCarlosAlberto
 */
public class Calculadora extends javax.swing.JFrame {//Clase Calculadora
//Variables
    String memoria1;
    String signo = "";
    String memoria2;
    String operacion;
    Boolean igualPrecionado = false;
    Boolean activo = false;
    Boolean restaAct = false;
    Boolean sumaAct = false;
    Boolean modAct = false;
    String cuenta = "";
    String resultado = "";
    String memoria = "0";
    String mod1;
    String mod2;
    String porcentaje1;
    String porcentaje2;
    Boolean porsentajeActivo = false;
    Boolean puntoActivo = false;
//Variables
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {//Constructor
        initComponents();
        setLocationRelativeTo(null);

        txtPantalla.requestFocus();//Solicitar enfoque a txtPantalla

        txtPantalla.addKeyListener(new KeyAdapter() {//KeyListener

            public void keyPressed(KeyEvent ke) {//keyPressed

                if (ke.getKeyCode() == KeyEvent.VK_L && ke.isControlDown()) {//if
                    btn_memClear.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_R && ke.isControlDown()) {
                    btn_memRecall.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_M && ke.isControlDown()) {
                    btn_memSave.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_P && ke.isControlDown()) {
                    btn_mMas.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_Q && ke.isControlDown()) {
                    btn_mMenos.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
                    btnBorrarPantalla.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_ESCAPE) {
                    btnBorrarOperacion.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_0 || ke.getKeyCode() == KeyEvent.VK_NUMPAD0) {
                    btn0.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_1 || ke.getKeyCode() == KeyEvent.VK_NUMPAD1) {
                    bnt1.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_2 || ke.getKeyCode() == KeyEvent.VK_NUMPAD2) {
                    btn2.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_3 || ke.getKeyCode() == KeyEvent.VK_NUMPAD3) {
                    btn3.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_4 || ke.getKeyCode() == KeyEvent.VK_NUMPAD4) {
                    bnt4.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_5 || ke.getKeyCode() == KeyEvent.VK_NUMPAD5) {
                    btn5.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_6 || ke.getKeyCode() == KeyEvent.VK_NUMPAD6) {
                    btn6.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_7 || ke.getKeyCode() == KeyEvent.VK_NUMPAD7) {
                    btn7.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_8 || ke.getKeyCode() == KeyEvent.VK_NUMPAD8) {
                    btn8.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_9 || ke.getKeyCode() == KeyEvent.VK_NUMPAD9) {
                    btn9.doClick();
                } else if (ke.getKeyCode() == 107 || ke.getKeyCode() == 521) {
                    btnMas.doClick();
                } else if (ke.getKeyCode() == 109 || ke.getKeyCode() == KeyEvent.VK_MINUS) {
                    btnMenos.doClick();
                } else if (ke.getKeyCode() == 106 || ke.getKeyCode() == KeyEvent.VK_ASTERISK) {
                    btnPor.doClick();
                } else if (ke.getKeyCode() == KeyEvent.VK_SLASH || ke.getKeyCode() == 111) {
                    btnDividir.doClick();
                } else if (ke.getKeyCode() == 10) {
                    bntIgual.doClick();
                } else if (ke.getKeyCode() == 110 || ke.getKeyCode() == 46) {
                    btnPunto.doClick();
                }

            }//keyPressed

        });//KeyListener

    }//Constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_error = new javax.swing.JLabel();
        lbl_indicador = new javax.swing.JLabel();
        txtPantalla = new javax.swing.JTextField();
        bnt1 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        bnt4 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        bntMasMenos = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnMas = new javax.swing.JButton();
        btnPor = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnBorrarOperacion = new javax.swing.JButton();
        btnBorrarPantalla = new javax.swing.JButton();
        btnInvertir = new javax.swing.JButton();
        bntIgual = new javax.swing.JButton();
        txtOperacion = new javax.swing.JTextField();
        btn_BorrarDigito = new javax.swing.JButton();
        btn_memClear = new javax.swing.JButton();
        btn_memRecall = new javax.swing.JButton();
        btn_memSave = new javax.swing.JButton();
        btn_mMas = new javax.swing.JButton();
        btn_mMenos = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        btn_Porsentaje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        lbl_error.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_error.setText("E");

        lbl_indicador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_indicador.setText("M");

        txtPantalla.setEditable(false);
        txtPantalla.setBackground(new java.awt.Color(255, 255, 255));
        txtPantalla.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPantalla.setText("0");
        txtPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPantallaActionPerformed(evt);
            }
        });

        bnt1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        bnt1.setText("1");
        bnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt1ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        bnt4.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        bnt4.setText("4");
        bnt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt4ActionPerformed(evt);
            }
        });

        btn0.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        bntMasMenos.setText("+/-");
        bntMasMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMasMenosActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnMenos.setText("-");
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        btnMas.setText("+");
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        btnPor.setText("*");
        btnPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorActionPerformed(evt);
            }
        });

        btnDividir.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btnDividir.setText("/");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        btnBorrarOperacion.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btnBorrarOperacion.setText("C");
        btnBorrarOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarOperacionActionPerformed(evt);
            }
        });

        btnBorrarPantalla.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btnBorrarPantalla.setText("CE");
        btnBorrarPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarPantallaActionPerformed(evt);
            }
        });

        btnInvertir.setText("1/x");
        btnInvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvertirActionPerformed(evt);
            }
        });

        bntIgual.setText("=");
        bntIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntIgualActionPerformed(evt);
            }
        });

        txtOperacion.setEditable(false);
        txtOperacion.setBackground(new java.awt.Color(255, 255, 255));
        txtOperacion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtOperacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOperacionFocusGained(evt);
            }
        });

        btn_BorrarDigito.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btn_BorrarDigito.setText("<=");
        btn_BorrarDigito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BorrarDigitoActionPerformed(evt);
            }
        });

        btn_memClear.setText("MC");
        btn_memClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_memClearActionPerformed(evt);
            }
        });

        btn_memRecall.setText("MR");
        btn_memRecall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_memRecallActionPerformed(evt);
            }
        });

        btn_memSave.setText("MS");
        btn_memSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_memSaveActionPerformed(evt);
            }
        });

        btn_mMas.setText("M+");
        btn_mMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mMasActionPerformed(evt);
            }
        });

        btn_mMenos.setText("M-");
        btn_mMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mMenosActionPerformed(evt);
            }
        });

        btn_mod.setText("MOD");
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        btn_Porsentaje.setText("%");
        btn_Porsentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PorsentajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnPor, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bnt4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bnt1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bntMasMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(bntIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_indicador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_error))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_memClear)
                                .addGap(6, 6, 6)
                                .addComponent(btn_memRecall)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_memSave)
                                .addGap(6, 6, 6)
                                .addComponent(btn_mMas)
                                .addGap(6, 6, 6)
                                .addComponent(btn_mMenos))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnInvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_Porsentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_mod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnBorrarPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(btnBorrarOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(btn_BorrarDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(txtOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_indicador, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_memClear)
                    .addComponent(btn_memRecall)
                    .addComponent(btn_memSave)
                    .addComponent(btn_mMas)
                    .addComponent(btn_mMenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInvertir)
                    .addComponent(btn_mod)
                    .addComponent(btn_Porsentaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBorrarPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BorrarDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bnt4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bnt1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntMasMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPantallaActionPerformed

    private void bnt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt1ActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        
        if (!resultado.equals("")) {
            txtPantalla.setText("");
            resultado = "";
        }
        if (txtPantalla.getText().equals("0") && txtPantalla.getText().length() <= 9) {
            txtPantalla.setText("");
            txtPantalla.setText(txtPantalla.getText() + "1");
        } else if (txtPantalla.getText().length() <= 9){
            txtPantalla.setText(txtPantalla.getText() + "1");
        }
    }//GEN-LAST:event_bnt1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        txtPantalla.requestFocus();
        if (!resultado.equals("")) {
            txtPantalla.setText("");
            resultado = "";
        }
        if (txtPantalla.getText().equals("0") && txtPantalla.getText().length() <= 9) {

            txtPantalla.setText("");
            txtPantalla.setText(txtPantalla.getText() + "2");
        } else if (txtPantalla.getText().length() <= 9){
            txtPantalla.setText(txtPantalla.getText() + "2");
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        if (!resultado.equals("")) {
            txtPantalla.setText("");
            resultado = "";
        }
        if (txtPantalla.getText().equals("0") && txtPantalla.getText().length() <= 9) {

            txtPantalla.setText("");
            txtPantalla.setText(txtPantalla.getText() + "3");
        } else if (txtPantalla.getText().length() <= 9){
            txtPantalla.setText(txtPantalla.getText() + "3");
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void bnt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt4ActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        txtPantalla.requestFocus();
        if (!resultado.equals("")) {
            txtPantalla.setText("");
            resultado = "";
        }
        if (txtPantalla.getText().equals("0") && txtPantalla.getText().length() <= 9) {

            txtPantalla.setText("");
            txtPantalla.setText(txtPantalla.getText() + "4");
        } else if (txtPantalla.getText().length() <= 9){
            txtPantalla.setText(txtPantalla.getText() + "4");
        }
    }//GEN-LAST:event_bnt4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        if (!resultado.equals("")) {
            txtPantalla.setText("");
            resultado = "";
        }
        if (txtPantalla.getText().equals("0") && txtPantalla.getText().length() <= 9) {

            txtPantalla.setText("");
            txtPantalla.setText(txtPantalla.getText() + "5");
        } else if (txtPantalla.getText().length() <= 9){
            txtPantalla.setText(txtPantalla.getText() + "5");
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        if (!resultado.equals("")) {
            txtPantalla.setText("");
            resultado = "";
        }
        if (txtPantalla.getText().equals("0") && txtPantalla.getText().length() <= 9) {

            txtPantalla.setText("");
            txtPantalla.setText(txtPantalla.getText() + "6");
        } else if (txtPantalla.getText().length() <= 9){
            txtPantalla.setText(txtPantalla.getText() + "6");
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        if (!resultado.equals("")) {
            txtPantalla.setText("");
            resultado = "";
        }
        if (txtPantalla.getText().equals("0") && txtPantalla.getText().length() <= 9) {

            txtPantalla.setText("");
            txtPantalla.setText(txtPantalla.getText() + "7");
        } else if (txtPantalla.getText().length() <= 9){
            txtPantalla.setText(txtPantalla.getText() + "7");
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        if (!resultado.equals("")) {
            txtPantalla.setText("");
            resultado = "";
        }
        if (txtPantalla.getText().equals("0") && txtPantalla.getText().length() <= 9) {

            txtPantalla.setText("");
            txtPantalla.setText(txtPantalla.getText() + "8");
        } else if (txtPantalla.getText().length() <= 9){
            txtPantalla.setText(txtPantalla.getText() + "8");
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        if (!resultado.equals("")) {
            txtPantalla.setText("");
            resultado = "";
        }
        if (txtPantalla.getText().equals("0") && txtPantalla.getText().length() <= 9) {

            txtPantalla.setText("");
            txtPantalla.setText(txtPantalla.getText() + "9");
        } else if (txtPantalla.getText().length() <= 9) {
            txtPantalla.setText(txtPantalla.getText() + "9");
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        if (!resultado.equals("")) {
            txtPantalla.setText("");
            resultado = "";
        }
        if (txtPantalla.getText().equals("0") && txtPantalla.getText().length() <= 9) {

            txtPantalla.setText("");
            txtPantalla.setText(txtPantalla.getText() + "0");
        } else if (txtPantalla.getText().length() <= 9){
            txtPantalla.setText(txtPantalla.getText() + "0");
        }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        //variable cadena para almacenar el texto de la pantalla de la calculadora
        puntoActivo = true;
        String cadena;
        cadena = txtPantalla.getText();
        //comparacion para saber si la cadena esta vacia
        if (cadena.length() <= 0) {
            txtPantalla.setText("o.");

        } else if (!existePunto(txtPantalla.getText())) {
            txtPantalla.setText(txtPantalla.getText() + ".");

        }
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnBorrarOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarOperacionActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        txtPantalla.setText("0");
        txtOperacion.setText("");
        cuenta = "";
        
        memoria1 = "";
        memoria2 = "";
        signo = "";
        resultado = "";
        puntoActivo = false;
        mod1 = "";
        mod2 = "";
        porcentaje1 = "";
        porcentaje2 = "";
        modAct = false;
        lbl_error.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnBorrarOperacionActionPerformed

    private void btnBorrarPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarPantallaActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        txtPantalla.setText("0");
        lbl_error.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnBorrarPantallaActionPerformed

    private void btnInvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvertirActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        String cadena;
        Double num;
        cadena = txtPantalla.getText();

        if (cadena.length() > 0) {
            num = 1 / (Double.parseDouble(cadena));
            txtPantalla.setText(num.toString());
        }
    }//GEN-LAST:event_btnInvertirActionPerformed

    private void bntMasMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMasMenosActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        Double num;
        String cadena;
        cadena = txtPantalla.getText();

        if (cadena.length() > 0) {
            num = (-1) * Double.parseDouble(cadena);
            txtPantalla.setText(num.toString());
        }
    }//GEN-LAST:event_bntMasMenosActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
//        
//        String resta;

        if (!signo.equals("") && igualPrecionado == false) {

            if (!txtPantalla.getText().equals("")) {

                memoria2 = txtPantalla.getText();

            } else {
                memoria2 = "0";
            }

            operacion = calculadora(memoria1, memoria2, signo);
            memoria1 = operacion;
            signo = "-";
            cuenta = cuenta + " " + txtPantalla.getText() + " " + signo;
            txtOperacion.setText(cuenta);
            txtPantalla.setText("");
            igualPrecionado = false;

        } else {

            igualPrecionado = false;
            if (!txtPantalla.getText().equals("")) {
               
                memoria1 = txtPantalla.getText();

            } else {
                memoria1 = "0";
            }
            signo = "-";
            cuenta = cuenta + " " + txtPantalla.getText() + " " + signo;
            txtOperacion.setText(cuenta);
            txtPantalla.setText("");
            restaAct = true;
        }

    }//GEN-LAST:event_btnMenosActionPerformed

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();

        if (!signo.equals("") && igualPrecionado == false) {

            if (!txtPantalla.getText().equals("")) {

                memoria2 = txtPantalla.getText();

            } else {
                memoria2 = "0";
            }

            operacion = calculadora(memoria1, memoria2, signo);
            memoria1 = operacion;
            signo = "+";
            cuenta = cuenta + " " + txtPantalla.getText() + " " + signo;
            txtOperacion.setText(cuenta);
            txtPantalla.setText("");
            igualPrecionado = false;

        } else {

            igualPrecionado = false;
            if (!txtPantalla.getText().equals("")) {
                
                memoria1 = txtPantalla.getText();

            } else {
                memoria1 = "0";
            }
            signo = "+";
            cuenta = cuenta + " " + txtPantalla.getText() + " " + signo;
            txtOperacion.setText(cuenta);
            txtPantalla.setText("");
            restaAct = true;
        }

    }//GEN-LAST:event_btnMasActionPerformed

    private void btnPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();

        if (!signo.equals("") && igualPrecionado == false) {

            if (!txtPantalla.getText().equals("")) {

                memoria2 = txtPantalla.getText();

            } else {
                memoria2 = "0";
            }

            operacion = calculadora(memoria1, memoria2, signo);
            memoria1 = operacion;
            signo = "*";
            cuenta = cuenta + " " + txtPantalla.getText() + " " + signo;
            txtOperacion.setText(cuenta);
            txtPantalla.setText("");
            igualPrecionado = false;

        } else {

            igualPrecionado = false;
            if (!txtPantalla.getText().equals("")) {
                
                memoria1 = txtPantalla.getText();

            } else {
                memoria1 = "0";
            }
            signo = "*";
            cuenta = cuenta + " " + txtPantalla.getText() + " " + signo;
            txtOperacion.setText(cuenta);
            txtPantalla.setText("");
            restaAct = true;
        }
    }//GEN-LAST:event_btnPorActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();

        if (!signo.equals("") && igualPrecionado == false) {

            if (!txtPantalla.getText().equals("")) {

                memoria2 = txtPantalla.getText();

            } else {
                memoria2 = "0";
            }

            operacion = calculadora(memoria1, memoria2, signo);
            memoria1 = operacion;
            signo = "/";
            cuenta = cuenta + " " + txtPantalla.getText() + " " + signo;
            txtOperacion.setText(cuenta);
            txtPantalla.setText("");
            igualPrecionado = false;

        } else {

            igualPrecionado = false;
            if (!txtPantalla.getText().equals("")) {
               
                memoria1 = txtPantalla.getText();

            } else {
                memoria1 = "0";
            }
            signo = "/";
            cuenta = cuenta + " " + txtPantalla.getText() + " " + signo;
            txtOperacion.setText(cuenta);
            txtPantalla.setText("");
            restaAct = true;
        }
        
    }//GEN-LAST:event_btnDividirActionPerformed

    private void bntIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntIgualActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();

        int modOp;
        double porsOp;
        String modRes;

        if (txtPantalla.getText().length() == 10) {
            lbl_error.setForeground(Color.red);
        } else {

            if (igualPrecionado == false) {

                if (modAct == true) {

                    mod2 = txtPantalla.getText();
                    modOp = Integer.parseInt(mod1) % Integer.parseInt(mod2);
                    modRes = Integer.toString(modOp);
                    txtPantalla.setText(modRes);
                    modAct = false;
                } else if (porsentajeActivo == true) {
                    porcentaje2 = txtPantalla.getText();
                    porsOp = (Double.parseDouble(porcentaje1) * Double.parseDouble(porcentaje2)) / 100;
                    modRes = Double.toString(porsOp);
                    txtPantalla.setText(modRes);
                    porsentajeActivo = false;
                } else {

                    memoria2 = txtPantalla.getText();
                    txtOperacion.setText("");
                    cuenta = "";

                    if (!memoria2.equals("")) {
                        resultado = calculadora(memoria1, memoria2, signo);
                        txtPantalla.setText(resultado);
                        
                        igualPrecionado = true;
                        activo = false;
                        restaAct = false;
                        sumaAct = false;
                    }
                }

            } else {

                memoria1 = txtPantalla.getText();
                resultado = calculadora(memoria1, memoria2, signo);

                txtPantalla.setText(resultado);
                
                igualPrecionado = true;
            }

        }

    }//GEN-LAST:event_bntIgualActionPerformed

    private void btn_BorrarDigitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BorrarDigitoActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        String cadena;
        cadena = txtPantalla.getText();

        if (cadena.length() > 0) {
            cadena = cadena.substring(0, cadena.length() - 1);
            txtPantalla.setText(cadena);
        }
    }//GEN-LAST:event_btn_BorrarDigitoActionPerformed

    private void btn_memSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_memSaveActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();

        if (txtPantalla.getText().equals("")) {
            memoria = "0";
        } else {

            memoria = txtPantalla.getText();
        }

        txtPantalla.setText("");
        lbl_indicador.setForeground(Color.GREEN);
    }//GEN-LAST:event_btn_memSaveActionPerformed

    private void btn_memRecallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_memRecallActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        txtPantalla.setText(memoria);
    }//GEN-LAST:event_btn_memRecallActionPerformed

    private void btn_memClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_memClearActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        memoria = "0";
        lbl_indicador.setForeground(Color.black);

    }//GEN-LAST:event_btn_memClearActionPerformed

    private void btn_mMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mMasActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        lbl_indicador.setForeground(Color.GREEN);
        memoria1 = memoria;
        if (txtPantalla.getText().equals("")) {
            memoria2 = "0";
        } else {

            memoria2 = txtPantalla.getText();
        }

        signo = "+";
        memoria = calculadora(memoria1, memoria2, signo);
        txtPantalla.setText("");


    }//GEN-LAST:event_btn_mMasActionPerformed

    private void btn_mMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mMenosActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();
        lbl_indicador.setForeground(Color.GREEN);
        memoria1 = memoria;
        if (txtPantalla.getText().equals("")) {
            memoria2 = "0";
        } else {

            memoria2 = txtPantalla.getText();
        }

        signo = "-";
        memoria = calculadora(memoria1, memoria2, signo);
        txtPantalla.setText("");


    }//GEN-LAST:event_btn_mMenosActionPerformed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        // TODO add your handling code here:
        txtPantalla.requestFocus();

        igualPrecionado = false;

        mod1 = txtPantalla.getText();

        txtOperacion.setText(mod1 + " MOD ");
        modAct = true;

        txtPantalla.setText("");

//        
//        
//        
//       }
//            mod1 = Integer.parseInt(txtPantalla.getText());

    }//GEN-LAST:event_btn_modActionPerformed

    private void txtOperacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOperacionFocusGained
        // TODO add your handling code here:
        txtPantalla.requestFocus();
    }//GEN-LAST:event_txtOperacionFocusGained

    private void btn_PorsentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PorsentajeActionPerformed
        // TODO add your handling code here:

        igualPrecionado = false;

        porcentaje1 = txtPantalla.getText();

        txtOperacion.setText(porcentaje1 + " % ");
        porsentajeActivo = true;

        txtPantalla.setText("");


    }//GEN-LAST:event_btn_PorsentajeActionPerformed

    public static String calculadora(String memoria1, String memoria2, String signo) {
        Double resultado = 0.0;
        String respuesta;

        if (signo.equals("-")) {
            resultado = Double.parseDouble(memoria1) - Double.parseDouble(memoria2);
        }
        if (signo.equals("+")) {
            resultado = Double.parseDouble(memoria1) + Double.parseDouble(memoria2);
        }
        if (signo.equals("*")) {
            resultado = Double.parseDouble(memoria1) * Double.parseDouble(memoria2);
        }
        if (signo.equals("/")) {
            resultado = Double.parseDouble(memoria1) / Double.parseDouble(memoria2);

        }

        DecimalFormat format = new DecimalFormat("0.#");

        respuesta = format.format(resultado);

        if (respuesta.length() > 9) {
            respuesta = respuesta.substring(0, 10);
        }

        return respuesta;

    }

    public static boolean existePunto(String cadena) {
        boolean resultado;
        resultado = false;

        for (int i = 0; i < cadena.length(); i++) {
            if (cadena.substring(i, i + 1).equals(".")) {
                resultado = true;
                break;

            }

        }
        return resultado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt1;
    private javax.swing.JButton bnt4;
    private javax.swing.JButton bntIgual;
    private javax.swing.JButton bntMasMenos;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrarOperacion;
    private javax.swing.JButton btnBorrarPantalla;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnInvertir;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnPor;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btn_BorrarDigito;
    private javax.swing.JButton btn_Porsentaje;
    private javax.swing.JButton btn_mMas;
    private javax.swing.JButton btn_mMenos;
    private javax.swing.JButton btn_memClear;
    private javax.swing.JButton btn_memRecall;
    private javax.swing.JButton btn_memSave;
    private javax.swing.JButton btn_mod;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_indicador;
    private javax.swing.JTextField txtOperacion;
    private javax.swing.JTextField txtPantalla;
    // End of variables declaration//GEN-END:variables

}//Fin Clase Calculadora
